# Generated by Django 2.1 on 2018-08-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_merge_20180817_1431'),
        ('mainapp', '0037_merge_20180817_1911'),
    ]

    operations = [
    ]
