# Generated by Django 2.1 on 2018-08-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_auto_20180818_0328'),
        ('mainapp', '0038_merge_20180817_2316'),
    ]

    operations = [
    ]
