# Generated by Django 2.1 on 2018-08-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_auto_20180818_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
