# Generated by Django 2.1 on 2018-08-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_merge_20180818_0957'),
        ('mainapp', '0042_auto_20180818_1329'),
    ]

    operations = [
    ]
