# Generated by Django 2.1 on 2018-08-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_volunteer_is_active'),
        ('mainapp', '0043_merge_20180818_1410'),
    ]

    operations = [
    ]
