# Generated by Django 2.1 on 2018-08-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_merge_20180818_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='is_request_for_others',
            field=models.BooleanField(default=False, help_text='Use below map to tell us their location', verbose_name='Requesting for others - മറ്റൊരാൾക്ക് വേണ്ടി അപേക്ഷിക്കുന്നു  '),
        ),
    ]
