# Generated by Django 2.1 on 2018-08-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_merge_20180818_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='link',
        ),
        migrations.AddField(
            model_name='announcements',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='announcements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/image_uploads'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcements',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', max_length=20, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='announcements/attachement_uploads'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='category',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Food'), (2, 'Camps'), (3, 'Weather'), (4, 'All')], verbose_name='Type'),
        ),
    ]
