# Generated by Django 2.1 on 2018-08-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_merge_20180818_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuecamp',
            name='total_people',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of People'),
        ),
    ]
