# Generated by Django 2.1 on 2018-08-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_auto_20180818_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='category',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='district',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='name',
        ),
    ]
