# Generated by Django 2.1 on 2018-08-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20180818_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
