# Generated by Django 2.1 on 2018-08-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_rescuecamp_total_people'),
        ('mainapp', '0048_auto_20180818_2136'),
    ]

    operations = [
    ]
