# Generated by Django 2.1 on 2018-08-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20180818_2000'),
        ('mainapp', '0049_merge_20180818_2150'),
    ]

    operations = [
    ]
