# Generated by Django 2.1 on 2018-08-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_auto_20180819_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Rescue: Request', 'verbose_name_plural': 'Rescue:Requests'},
        ),
    ]
