# Generated by Django 2.1 on 2018-08-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_auto_20180819_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuecamp',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10),
        ),
    ]
