# Generated by Django 2.1 on 2018-08-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0058_auto_20180819_2137'),
        ('mainapp', '0058_auto_20180819_2021'),
    ]

    operations = [
    ]
