# Generated by Django 2.1 on 2018-08-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0060_auto_20180820_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuecamp',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('duplicate', 'Duplicate')], default='active', max_length=10),
        ),
    ]
