# Generated by Django 2.1 on 2018-08-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0062_volunteer_has_consented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='has_consented',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
    ]
