# Generated by Django 2.1 on 2018-08-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0063_auto_20180821_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateRescueCamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Camp Name - ക്യാമ്പിന്റെ പേര്')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Address - അഡ്രസ്')),
                ('district', models.CharField(choices=[('alp', 'Alappuzha - ആലപ്പുഴ'), ('ekm', 'Ernakulam - എറണാകുളം'), ('idk', 'Idukki - ഇടുക്കി'), ('knr', 'Kannur - കണ്ണൂർ'), ('ksr', 'Kasaragod - കാസർഗോഡ്'), ('kol', 'Kollam - കൊല്ലം'), ('ktm', 'Kottayam - കോട്ടയം'), ('koz', 'Kozhikode - കോഴിക്കോട്'), ('mpm', 'Malappuram - മലപ്പുറം'), ('pkd', 'Palakkad - പാലക്കാട്'), ('ptm', 'Pathanamthitta - പത്തനംതിട്ട'), ('tvm', 'Thiruvananthapuram - തിരുവനന്തപുരം'), ('tcr', 'Thrissur - തൃശ്ശൂർ'), ('wnd', 'Wayanad - വയനാട്')], max_length=15)),
                ('taluk', models.CharField(max_length=50, verbose_name='Taluk - താലൂക്ക്')),
                ('village', models.CharField(max_length=50, verbose_name='Village - വില്ലജ്')),
                ('contacts', models.TextField(blank=True, null=True, verbose_name='Phone Numbers - ഫോൺ നമ്പറുകൾ')),
                ('facilities_available', models.TextField(blank=True, null=True, verbose_name='Facilities Available (light, kitchen, toilets etc.) - ലഭ്യമായ സൗകര്യങ്ങൾ')),
                ('map_link', models.CharField(blank=True, help_text='Copy and paste the full Google Maps link', max_length=250, null=True, verbose_name='Map link')),
                ('latlng', models.CharField(blank=True, help_text="Comma separated latlng field. Leave blank if you don't know it", max_length=100, verbose_name='GPS Coordinates')),
                ('total_people', models.IntegerField(blank=True, null=True, verbose_name='Total Number of People')),
                ('total_males', models.IntegerField(blank=True, null=True, verbose_name='Number of Males')),
                ('total_females', models.IntegerField(blank=True, null=True, verbose_name='Number of Females')),
                ('total_infants', models.IntegerField(blank=True, null=True, verbose_name='Number of Infants (<2y)')),
                ('food_req', models.TextField(blank=True, null=True, verbose_name='Food - ഭക്ഷണം')),
                ('clothing_req', models.TextField(blank=True, null=True, verbose_name='Clothing - വസ്ത്രം')),
                ('sanitary_req', models.TextField(blank=True, null=True, verbose_name='Sanitary - സാനിറ്ററി')),
                ('medical_req', models.TextField(blank=True, null=True, verbose_name='Medical - മെഡിക്കൽ')),
                ('other_req', models.TextField(blank=True, null=True, verbose_name='Other - മറ്റുള്ളവ')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('duplicate', 'Duplicate')], default='active', max_length=10)),
            ],
            options={
                'verbose_name': 'Private Relief: Camp',
                'verbose_name_plural': 'Private Relief: Camps',
            },
        ),
    ]
