# Generated by Django 2.1 on 2018-08-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0063_auto_20180821_0732'),
        ('mainapp', '0064_privaterescuecamp'),
    ]

    operations = [
    ]
