# Generated by Django 2.1 on 2018-08-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0062_collectioncenter'),
        ('mainapp', '0065_merge_20180821_1422'),
    ]

    operations = [
    ]
