# Generated by Django 2.1 on 2018-08-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0068_auto_20180821_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncenter',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='City - നഗരം'),
        ),
        migrations.AlterField(
            model_name='collectioncenter',
            name='is_inside_kerala',
            field=models.BooleanField(default=True, verbose_name='Center inside kerala? - കേന്ദ്രം കേരളത്തിലാണോ'),
        ),
    ]
