# Generated by Django 2.1 on 2018-08-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0068_auto_20180821_1710'),
        ('mainapp', '0064_auto_20180821_1147'),
    ]

    operations = [
    ]
