# Generated by Django 2.1 on 2018-08-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0068_auto_20180821_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='checkin_date',
            field=models.DateTimeField(null=True, verbose_name='Check-in Date - ചെക്ക്-ഇൻ തീയതി'),
        ),
        migrations.AddField(
            model_name='person',
            name='checkout_date',
            field=models.DateTimeField(null=True, verbose_name='Check-in Date - ചെക്ക്-ഔട്ട് തീയതി'),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('checked_out', 'Checked Out'), ('closed', 'Closed')], default=None, max_length=15, null=True),
        ),
    ]
