# Generated by Django 2.1 on 2018-08-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0071_csvfileupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CsvFileUpload',
            new_name='CsvBulkUpload',
        ),
    ]
