# Generated by Django 2.1 on 2018-08-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0072_auto_20180822_0000'),
        ('mainapp', '0071_auto_20180821_2358'),
    ]

    operations = [
    ]
