# Generated by Django 2.1 on 2018-08-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0074_auto_20180822_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='unique_identifier',
        ),
    ]
