# Generated by Django 2.1 on 2018-08-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0075_remove_person_unique_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='unique_identifier',
            field=models.CharField(default='', max_length=32),
        ),
    ]
