# Generated by Django 2.1 on 2018-08-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0078_auto_20180823_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvbulkupload',
            name='failure_reason',
            field=models.CharField(default='', max_length=150),
        ),
    ]
