# Generated by Django 2.1 on 2018-08-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0079_csvbulkupload_failure_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvbulkupload',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
