# Generated by Django 2.1 on 2018-08-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0082_auto_20180824_1147'),
        ('mainapp', '0082_collectioncenter_map_link'),
    ]

    operations = [
    ]
