# Generated by Django 2.1 on 2018-08-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0084_contributor_contribution_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='commodities',
        ),
        migrations.AddField(
            model_name='contributor',
            name='contrib_details',
            field=models.TextField(default='', verbose_name='Details of contribution Eg: 10 shirts'),
        ),
    ]
