# Generated by Django 2.1 on 2018-08-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0084_auto_20180824_1426'),
        ('mainapp', '0085_auto_20180824_1511'),
    ]

    operations = [
    ]
